# Generated by Django 2.1.7 on 2019-02-27 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/advices', verbose_name='Obraz')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/advices', verbose_name='Wideo')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name_plural': 'Porady motoryzacyjne',
            },
        ),
        migrations.CreateModel(
            name='AnswerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Odpowiedź')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name_plural': 'Odpowiedzi na posty',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name_plural': 'Kategorie zagadnień',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tag', to='main.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posty na forum',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Zdjęcie profilowe')),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
        migrations.CreateModel(
            name='TestTraing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('result', models.IntegerField(verbose_name='Wynik')),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Advice', verbose_name='Do której porady')),
            ],
            options={
                'verbose_name_plural': 'Dostępne treningi',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Treść pytania')),
                ('correct_answer', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Prawidłowa odpowiedź')),
                ('answer_a', models.TextField(verbose_name='Odpowiedź A')),
                ('file_a', models.FileField(blank=True, null=True, upload_to='answer_files/', verbose_name='Media A')),
                ('answer_b', models.TextField(verbose_name='Odpowiedź B')),
                ('file_b', models.FileField(blank=True, null=True, upload_to='answer_files/', verbose_name='Media B')),
                ('answer_c', models.TextField(verbose_name='Odpowiedź C')),
                ('file_c', models.FileField(blank=True, null=True, upload_to='answer_files/', verbose_name='Media C')),
                ('answer_d', models.TextField(verbose_name='Odpowiedź D')),
                ('file_d', models.FileField(blank=True, null=True, upload_to='answer_files/', verbose_name='Media D')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestTraing', verbose_name='Trening')),
            ],
            options={
                'verbose_name_plural': 'Pytania do treningu',
            },
        ),
        migrations.AddField(
            model_name='answerpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ForumPost', verbose_name='Post z forum'),
        ),
        migrations.AddField(
            model_name='answerpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AddField(
            model_name='advice',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.Category', verbose_name='Kategoria'),
        ),
    ]
